apiVersion: batch/v1
kind: Job
metadata:
  name: single-consumer
  namespace: strimzi
spec:
  template:
    spec:
      containers:
      - name: consumer
        image: registry.redhat.io/amq7/amq-streams-kafka-26-rhel7:1.7.0
        command:
        - /opt/kafka/bin/kafka-consumer-perf-test.sh
        - --bootstrap-server
        - strimzi-cluster-kafka-bootstrap:9092
        - --topic 
        - test-rep-one 
        - --messages 
        - '1600000000' 
        - --threads
        - '16'
      restartPolicy: Never
  backoffLimit: 4
